metainfo:
    gender: 'neutral'
    data_dir: /ubc/cs/home/c/chunjins/chunjin_shield/project/facavatar-release/data/zju_mocap/394_training.h5
    subject: "394"
    img_scale_factor: 0.5

    bgcolor: 0. # [0.,1.]
    bbox_offset: 0.3

testing:
    type: 'novel_view'

train:
    type: "Video"
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8
    skip: 1

    sampling_strategy: 'mixed_sampling' #'weighted_sampling' 'patch_sampling' 'mixed_sampling'
    num_sample: 576 #576 # for weighted_sampling
    sample_bbox_ratio: 0.7 # for weighted_sampling
    patch_size: 24 # for patch_sampling
    sample_subject_ratio: 0.9 # for patch_sampling
    N_patch: 2 # for patch_sampling

valid:
    type: "VideoVal"
    image_id: 0
    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8
    skip: 1

    use_refined_pose: True
    num_sample : -1
    pixel_per_batch: 2048

test:
    type: "VideoTest"
    image_id: 0
    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8
    skip: 1

    use_refined_pose: True
    num_sample : -1
    pixel_per_batch: 2048

novelpose:
    type: "VideoNovelPose"
    image_id: 0
    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8
    skip: 1

    use_refined_pose: False
    num_sample : -1
    pixel_per_batch: 2048

novelview:
    type: "VideoNovelView"
    image_id: 0
    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8
    skip: 1

    use_refined_pose: False
    num_sample : -1
    pixel_per_batch: 2048

freeview:
    type: "VideoFreeView"
    image_id: [0]
    degree: 30
    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8
    skip: 1

    use_refined_pose: True
    num_sample : -1
    pixel_per_batch: 2048

